//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDCGExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDCGExplorer.TextResource-en", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access 3DCG Mods Reference Server.
        /// </summary>
        internal static string AccessModsRefServer {
            get {
                return ResourceManager.GetString("AccessModsRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always create new tab.
        /// </summary>
        internal static string AlwaysNewTab {
            get {
                return ResourceManager.GetString("AlwaysNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archive folder window.
        /// </summary>
        internal static string AlwaysOpenFolderByExtract {
            get {
                return ResourceManager.GetString("AlwaysOpenFolderByExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive is null.
        /// </summary>
        internal static string ArchiveIsNull {
            get {
                return ResourceManager.GetString("ArchiveIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive not found.
        /// </summary>
        internal static string ArchiveNotFound {
            get {
                return ResourceManager.GetString("ArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcs Directory.
        /// </summary>
        internal static string ArcsDirectory {
            get {
                return ResourceManager.GetString("ArcsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arcnames server.
        /// </summary>
        internal static string ArcsNameServer {
            get {
                return ResourceManager.GetString("ArcsNameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcs.
        /// </summary>
        internal static string ArcsTabName {
            get {
                return ResourceManager.GetString("ArcsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.tah file read error.
        /// </summary>
        internal static string BaseTahReadError {
            get {
                return ResourceManager.GetString("BaseTahReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string CameraAutoCenter {
            get {
                return ResourceManager.GetString("CameraAutoCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string CameraCenter {
            get {
                return ResourceManager.GetString("CameraCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        internal static string CameraTransition {
            get {
                return ResourceManager.GetString("CameraTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision detect.
        /// </summary>
        internal static string CollisionDetection {
            get {
                return ResourceManager.GetString("CollisionDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision TAH.
        /// </summary>
        internal static string CollisionedTAH {
            get {
                return ResourceManager.GetString("CollisionedTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision from.
        /// </summary>
        internal static string CollisionFrom {
            get {
                return ResourceManager.GetString("CollisionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision from.
        /// </summary>
        internal static string CollisionHTML_CollisionFrom {
            get {
                return ResourceManager.GetString("CollisionHTML_CollisionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision to.
        /// </summary>
        internal static string CollisionHTML_CollisionTo {
            get {
                return ResourceManager.GetString("CollisionHTML_CollisionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision.
        /// </summary>
        internal static string CollisionsTabName {
            get {
                return ResourceManager.GetString("CollisionsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision to.
        /// </summary>
        internal static string CollisionTo {
            get {
                return ResourceManager.GetString("CollisionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress complete.
        /// </summary>
        internal static string CompressComplete {
            get {
                return ResourceManager.GetString("CompressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing.
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DataBaseMenu {
            get {
                return ResourceManager.GetString("DataBaseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database detting.
        /// </summary>
        internal static string DatabaseSetting {
            get {
                return ResourceManager.GetString("DatabaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database create/update.
        /// </summary>
        internal static string DataBaseUpdate {
            get {
                return ResourceManager.GetString("DataBaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date, Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete db file. Please delete manually..
        /// </summary>
        internal static string DBFileDeleteError {
            get {
                return ResourceManager.GetString("DBFileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tah of a different version is not a collision..
        /// </summary>
        internal static string DifferVersionTah {
            get {
                return ResourceManager.GetString("DifferVersionTah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show posefile to tso viewer.
        /// </summary>
        internal static string DisplayPoseTSOView {
            get {
                return ResourceManager.GetString("DisplayPoseTSOView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tso viwer.
        /// </summary>
        internal static string DisplayTSOView {
            get {
                return ResourceManager.GetString("DisplayTSOView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display latest information.
        /// </summary>
        internal static string DisplayUpdate {
            get {
                return ResourceManager.GetString("DisplayUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from mods database.
        /// </summary>
        internal static string DownloadCaption {
            get {
                return ResourceManager.GetString("DownloadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from mods database.
        /// </summary>
        internal static string DownloadLatestArcsnameszip {
            get {
                return ResourceManager.GetString("DownloadLatestArcsnameszip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit annotation....
        /// </summary>
        internal static string EditAnnotation {
            get {
                return ResourceManager.GetString("EditAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit annotation.
        /// </summary>
        internal static string EditAnnotationText {
            get {
                return ResourceManager.GetString("EditAnnotationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration.
        /// </summary>
        internal static string EditConfiguration {
            get {
                return ResourceManager.GetString("EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edinting.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration.
        /// </summary>
        internal static string EditSystemDatabase {
            get {
                return ResourceManager.GetString("EditSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit TAH file.
        /// </summary>
        internal static string EditTahFile {
            get {
                return ResourceManager.GetString("EditTahFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand tree.
        /// </summary>
        internal static string ExpandTree {
            get {
                return ResourceManager.GetString("ExpandTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extract failure.
        /// </summary>
        internal static string ExtractFailure {
            get {
                return ResourceManager.GetString("ExtractFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string ExtractFailureCaption {
            get {
                return ResourceManager.GetString("ExtractFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        internal static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success extract file.
        /// </summary>
        internal static string ExtractSuccess {
            get {
                return ResourceManager.GetString("ExtractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ExtractSuccessCaption {
            get {
                return ResourceManager.GetString("ExtractSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract TAH file.
        /// </summary>
        internal static string ExtractTahFile {
            get {
                return ResourceManager.GetString("ExtractTahFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extact archive file.
        /// </summary>
        internal static string ExtractZipFile {
            get {
                return ResourceManager.GetString("ExtractZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure.
        /// </summary>
        internal static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read error.
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reading now.
        /// </summary>
        internal static string FileReading {
            get {
                return ResourceManager.GetString("FileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesize.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filetype.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is used.
        /// </summary>
        internal static string FileUsed {
            get {
                return ResourceManager.GetString("FileUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find stray tah file.
        /// </summary>
        internal static string FindNoBaseMod {
            get {
                return ResourceManager.GetString("FindNoBaseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find stray tah file.
        /// </summary>
        internal static string FoundStrayArchive {
            get {
                return ResourceManager.GetString("FoundStrayArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find stray tah file.
        /// </summary>
        internal static string FoundStrayTAH {
            get {
                return ResourceManager.GetString("FoundStrayTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashcode.
        /// </summary>
        internal static string HashCode {
            get {
                return ResourceManager.GetString("HashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet access failure.
        /// </summary>
        internal static string HttpError {
            get {
                return ResourceManager.GetString("HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string InstalledModsTabName {
            get {
                return ResourceManager.GetString("InstalledModsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract prefrred archives.
        /// </summary>
        internal static string InstallPreferredMods {
            get {
                return ResourceManager.GetString("InstallPreferredMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always download 3DCG Mods Reference Server databases..
        /// </summary>
        internal static string LookupModRefServer {
            get {
                return ResourceManager.GetString("LookupModRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Dummy TAH file.
        /// </summary>
        internal static string MakeDummyTAH {
            get {
                return ResourceManager.GetString("MakeDummyTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Heavy Save file.
        /// </summary>
        internal static string MakeHeavySaveFile {
            get {
                return ResourceManager.GetString("MakeHeavySaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make TAH File.
        /// </summary>
        internal static string MakeTAHFile {
            get {
                return ResourceManager.GetString("MakeTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make TBN File.
        /// </summary>
        internal static string MakeTbnDialogText {
            get {
                return ResourceManager.GetString("MakeTbnDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Thumbnail.
        /// </summary>
        internal static string MakeThumbnail {
            get {
                return ResourceManager.GetString("MakeThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://3dcustom.ath.cx/TDCGExplorer/manual.html.
        /// </summary>
        internal static string MODRefServerUrl {
            get {
                return ResourceManager.GetString("MODRefServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD RegExp..
        /// </summary>
        internal static string MODRegExp {
            get {
                return ResourceManager.GetString("MODRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod ref. server.
        /// </summary>
        internal static string ModsRefServer {
            get {
                return ResourceManager.GetString("ModsRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tab.
        /// </summary>
        internal static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string NewTabCaption {
            get {
                return ResourceManager.GetString("NewTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be TAH Directory only.
        /// </summary>
        internal static string OnlyTAHDirectory {
            get {
                return ResourceManager.GetString("OnlyTAHDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be TAH File only.
        /// </summary>
        internal static string OnlyTAHFile {
            get {
                return ResourceManager.GetString("OnlyTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be TMO File only.
        /// </summary>
        internal static string OnlyTMOFile {
            get {
                return ResourceManager.GetString("OnlyTMOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be TSOFile only.
        /// </summary>
        internal static string OnlyTSOFile {
            get {
                return ResourceManager.GetString("OnlyTSOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all tah file under the this diretory..
        /// </summary>
        internal static string OpenAllTAH {
            get {
                return ResourceManager.GetString("OpenAllTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer open extected files folder..
        /// </summary>
        internal static string OpenArchive {
            get {
                return ResourceManager.GetString("OpenArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Graphics or Text file..
        /// </summary>
        internal static string OpenGraphicsOrText {
            get {
                return ResourceManager.GetString("OpenGraphicsOrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Text or Graphics file..
        /// </summary>
        internal static string OpenTextOrGraphics {
            get {
                return ResourceManager.GetString("OpenTextOrGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File(*.tdcgpose.png)|*.tdcgpose.png.
        /// </summary>
        internal static string PNGPoseFileDescription {
            get {
                return ResourceManager.GetString("PNGPoseFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File(*.tdcgsav.png)|*.tdcgsav.png.
        /// </summary>
        internal static string PNGSaveFileDescription {
            get {
                return ResourceManager.GetString("PNGSaveFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pose directory.
        /// </summary>
        internal static string PoseDirectory {
            get {
                return ResourceManager.GetString("PoseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pose file.
        /// </summary>
        internal static string PoseFileSetting {
            get {
                return ResourceManager.GetString("PoseFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer archive file.
        /// </summary>
        internal static string PreferredZipFile {
            get {
                return ResourceManager.GetString("PreferredZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive(s) extracted..
        /// </summary>
        internal static string PrefZip1 {
            get {
                return ResourceManager.GetString("PrefZip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive(s) not found..
        /// </summary>
        internal static string PrefZip2 {
            get {
                return ResourceManager.GetString("PrefZip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All preferred archive installed..
        /// </summary>
        internal static string PrefZip3 {
            get {
                return ResourceManager.GetString("PrefZip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string prefZip4 {
            get {
                return ResourceManager.GetString("prefZip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSD file read error.
        /// </summary>
        internal static string PSDFileReadError {
            get {
                return ResourceManager.GetString("PSDFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Heavy Save file.
        /// </summary>
        internal static string ReloadHeavySaveFile {
            get {
                return ResourceManager.GetString("ReloadHeavySaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render complete.
        /// </summary>
        internal static string RenderingComplete {
            get {
                return ResourceManager.GetString("RenderingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering....
        /// </summary>
        internal static string RenderingNow {
            get {
                return ResourceManager.GetString("RenderingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve data base.
        /// </summary>
        internal static string ResearchAssumptionArchive {
            get {
                return ResourceManager.GetString("ResearchAssumptionArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tso viewer.
        /// </summary>
        internal static string ResetTsoViwer {
            get {
                return ResourceManager.GetString("ResetTsoViwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same filename name is a collision..
        /// </summary>
        internal static string SameFileIsCollisioned {
            get {
                return ResourceManager.GetString("SameFileIsCollisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file now.
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust.
        /// </summary>
        internal static string SaveFileParam0 {
            get {
                return ResourceManager.GetString("SaveFileParam0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall.
        /// </summary>
        internal static string SaveFileParam1 {
            get {
                return ResourceManager.GetString("SaveFileParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm.
        /// </summary>
        internal static string SaveFileParam2 {
            get {
                return ResourceManager.GetString("SaveFileParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg.
        /// </summary>
        internal static string SaveFileParam3 {
            get {
                return ResourceManager.GetString("SaveFileParam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string SaveFileParam4 {
            get {
                return ResourceManager.GetString("SaveFileParam4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye.
        /// </summary>
        internal static string SaveFileParam5 {
            get {
                return ResourceManager.GetString("SaveFileParam5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soften.
        /// </summary>
        internal static string SaveFileParam6 {
            get {
                return ResourceManager.GetString("SaveFileParam6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savefile.
        /// </summary>
        internal static string SaveFilesTabName {
            get {
                return ResourceManager.GetString("SaveFilesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file viewer.
        /// </summary>
        internal static string SaveFileViewer {
            get {
                return ResourceManager.GetString("SaveFileViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save TAH file.
        /// </summary>
        internal static string SaveTAHFile {
            get {
                return ResourceManager.GetString("SaveTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected TMO file.
        /// </summary>
        internal static string SaveTMOFile {
            get {
                return ResourceManager.GetString("SaveTMOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval completion. It jumps to the file when the line is double-clicked..
        /// </summary>
        internal static string SearchComplete {
            get {
                return ResourceManager.GetString("SearchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach Keyword.
        /// </summary>
        internal static string SearchDialogLabel {
            get {
                return ResourceManager.GetString("SearchDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchDialogText {
            get {
                return ResourceManager.GetString("SearchDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with archive folder.
        /// </summary>
        internal static string SearchWithZipFile {
            get {
                return ResourceManager.GetString("SearchWithZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select save file name.
        /// </summary>
        internal static string SelectSaveFileName {
            get {
                return ResourceManager.GetString("SelectSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show manual.
        /// </summary>
        internal static string ShowManual {
            get {
                return ResourceManager.GetString("ShowManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TSO preview.
        /// </summary>
        internal static string ShowTSOPreview {
            get {
                return ResourceManager.GetString("ShowTSOPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version....
        /// </summary>
        internal static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Setting.
        /// </summary>
        internal static string StartupSetting {
            get {
                return ResourceManager.GetString("StartupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stray TAH name.
        /// </summary>
        internal static string StrayTAH {
            get {
                return ResourceManager.GetString("StrayTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stray TBN name.
        /// </summary>
        internal static string StrayTBN {
            get {
                return ResourceManager.GetString("StrayTBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded 3DCG MODS Reference Server.
        /// </summary>
        internal static string SuccessModRefServer {
            get {
                return ResourceManager.GetString("SuccessModRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Mortion Enable.
        /// </summary>
        internal static string SwitchToMortionEnabled {
            get {
                return ResourceManager.GetString("SwitchToMortionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab browser.
        /// </summary>
        internal static string TabBrowser {
            get {
                return ResourceManager.GetString("TabBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagnames server.
        /// </summary>
        internal static string TagNameServer {
            get {
                return ResourceManager.GetString("TagNameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string TagsTabName {
            get {
                return ResourceManager.GetString("TagsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH decrypt complete.
        /// </summary>
        internal static string TAHDecryptComplete {
            get {
                return ResourceManager.GetString("TAHDecryptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH Editor.
        /// </summary>
        internal static string TAHEditor {
            get {
                return ResourceManager.GetString("TAHEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change category selected files..
        /// </summary>
        internal static string TAHEditorChangeCategory {
            get {
                return ResourceManager.GetString("TAHEditorChangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color code selected files..
        /// </summary>
        internal static string TAHEditorChangeColorCode {
            get {
                return ResourceManager.GetString("TAHEditorChangeColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tah information..
        /// </summary>
        internal static string TAHEditorChangeTAHInformation {
            get {
                return ResourceManager.GetString("TAHEditorChangeTAHInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose tah file from selected files..
        /// </summary>
        internal static string TAHEditorComposeTAHFile {
            get {
                return ResourceManager.GetString("TAHEditorComposeTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected files..
        /// </summary>
        internal static string TAHEditorFileDelete {
            get {
                return ResourceManager.GetString("TAHEditorFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tbn file from selected tso files..
        /// </summary>
        internal static string TAHEditorMakeTBN {
            get {
                return ResourceManager.GetString("TAHEditorMakeTBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color code is 2 character only..
        /// </summary>
        internal static string TAHEditorNewColorNoError {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New color code.
        /// </summary>
        internal static string TAHEditorNewColorNoLabel {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color code.
        /// </summary>
        internal static string TAHEditorNewColorNoText {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH editor place.
        /// </summary>
        internal static string TAHEditorPlace {
            get {
                return ResourceManager.GetString("TAHEditorPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change selected file name..
        /// </summary>
        internal static string TAHEditorRename {
            get {
                return ResourceManager.GetString("TAHEditorRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change selected file name..
        /// </summary>
        internal static string TAHEditorRenameLabel {
            get {
                return ResourceManager.GetString("TAHEditorRenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string TAHEditorRenameText {
            get {
                return ResourceManager.GetString("TAHEditorRenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write selected file..
        /// </summary>
        internal static string TAHEditorSaveSelectedFile {
            get {
                return ResourceManager.GetString("TAHEditorSaveSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBN category.
        /// </summary>
        internal static string TAHEditorTbnCatChangeLabel {
            get {
                return ResourceManager.GetString("TAHEditorTbnCatChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tbn category selected file..
        /// </summary>
        internal static string TAHEditorTbnCatChangeText {
            get {
                return ResourceManager.GetString("TAHEditorTbnCatChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH compose complete..
        /// </summary>
        internal static string TAHEncryptComplete {
            get {
                return ResourceManager.GetString("TAHEncryptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH File.
        /// </summary>
        internal static string TAHFile {
            get {
                return ResourceManager.GetString("TAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH File(*.tah)|*.tah.
        /// </summary>
        internal static string TAHFileDescription {
            get {
                return ResourceManager.GetString("TAHFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tah file exceeds 4GB. Please adjust the consolidated tah file to 4GB or less..
        /// </summary>
        internal static string TAHFileLimitError {
            get {
                return ResourceManager.GetString("TAHFileLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH Filename.
        /// </summary>
        internal static string TAHFilename {
            get {
                return ResourceManager.GetString("TAHFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH file read error..
        /// </summary>
        internal static string TAHFileReadError {
            get {
                return ResourceManager.GetString("TAHFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH file loading....
        /// </summary>
        internal static string TAHFileReading {
            get {
                return ResourceManager.GetString("TAHFileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH internal file search....
        /// </summary>
        internal static string tahfilesearch {
            get {
                return ResourceManager.GetString("tahfilesearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH header information.
        /// </summary>
        internal static string TAHInformation {
            get {
                return ResourceManager.GetString("TAHInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH Version.
        /// </summary>
        internal static string TAHVersion {
            get {
                return ResourceManager.GetString("TAHVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze tbn files....
        /// </summary>
        internal static string TBNAnalyze {
            get {
                return ResourceManager.GetString("TBNAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:Eyebrow.
        /// </summary>
        internal static string TbnCat0 {
            get {
                return ResourceManager.GetString("TbnCat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:Oblique tooth.
        /// </summary>
        internal static string TbnCat1 {
            get {
                return ResourceManager.GetString("TbnCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:Mole.
        /// </summary>
        internal static string TbnCat2 {
            get {
                return ResourceManager.GetString("TbnCat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:Earrings.
        /// </summary>
        internal static string TbnCat3 {
            get {
                return ResourceManager.GetString("TbnCat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:Body.
        /// </summary>
        internal static string TbnCatA {
            get {
                return ResourceManager.GetString("TbnCatA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B:Front hair.
        /// </summary>
        internal static string TbnCatB {
            get {
                return ResourceManager.GetString("TbnCatB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:Back hair.
        /// </summary>
        internal static string TbnCatC {
            get {
                return ResourceManager.GetString("TbnCatC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:Hair borders.
        /// </summary>
        internal static string TbnCatD {
            get {
                return ResourceManager.GetString("TbnCatD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:Pupil.
        /// </summary>
        internal static string TbnCatE {
            get {
                return ResourceManager.GetString("TbnCatE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string TbnCatEx0 {
            get {
                return ResourceManager.GetString("TbnCatEx0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H scene.
        /// </summary>
        internal static string TbnCatEx1 {
            get {
                return ResourceManager.GetString("TbnCatEx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:Bra.
        /// </summary>
        internal static string TbnCatF {
            get {
                return ResourceManager.GetString("TbnCatF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:Whole body undergarment.
        /// </summary>
        internal static string TbnCatG {
            get {
                return ResourceManager.GetString("TbnCatG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H:Pants.
        /// </summary>
        internal static string TbnCatH {
            get {
                return ResourceManager.GetString("TbnCatH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I:Socks.
        /// </summary>
        internal static string TbnCatI {
            get {
                return ResourceManager.GetString("TbnCatI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J:Jacket.
        /// </summary>
        internal static string TbnCatJ {
            get {
                return ResourceManager.GetString("TbnCatJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K:Whole body jacket.
        /// </summary>
        internal static string TbnCatK {
            get {
                return ResourceManager.GetString("TbnCatK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:Jacket option..
        /// </summary>
        internal static string TbnCatL {
            get {
                return ResourceManager.GetString("TbnCatL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M:Skirt.
        /// </summary>
        internal static string TbnCatM {
            get {
                return ResourceManager.GetString("TbnCatM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:Tail.
        /// </summary>
        internal static string TbnCatN {
            get {
                return ResourceManager.GetString("TbnCatN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:Shoes.
        /// </summary>
        internal static string TbnCatO {
            get {
                return ResourceManager.GetString("TbnCatO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P:Head equipment.
        /// </summary>
        internal static string TbnCatP {
            get {
                return ResourceManager.GetString("TbnCatP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q:Glasses.
        /// </summary>
        internal static string TbnCatQ {
            get {
                return ResourceManager.GetString("TbnCatQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R:Collar.
        /// </summary>
        internal static string TbnCatR {
            get {
                return ResourceManager.GetString("TbnCatR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:Arm equipment.
        /// </summary>
        internal static string TbnCatS {
            get {
                return ResourceManager.GetString("TbnCatS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:Back.
        /// </summary>
        internal static string TbnCatT {
            get {
                return ResourceManager.GetString("TbnCatT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U:Hair option.
        /// </summary>
        internal static string TbnCatU {
            get {
                return ResourceManager.GetString("TbnCatU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V:Eyepatch.
        /// </summary>
        internal static string TbnCatV {
            get {
                return ResourceManager.GetString("TbnCatV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W:Tights garters.
        /// </summary>
        internal static string TbnCatW {
            get {
                return ResourceManager.GetString("TbnCatW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:Wrist.
        /// </summary>
        internal static string TbnCatX {
            get {
                return ResourceManager.GetString("TbnCatX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:Ribbon.
        /// </summary>
        internal static string TbnCatY {
            get {
                return ResourceManager.GetString("TbnCatY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:Hand reserves.
        /// </summary>
        internal static string TbnCatZ {
            get {
                return ResourceManager.GetString("TbnCatZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbn file read error.
        /// </summary>
        internal static string TBNReadError {
            get {
                return ResourceManager.GetString("TBNReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDCG directory.
        /// </summary>
        internal static string TDCGDirectory {
            get {
                return ResourceManager.GetString("TDCGDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMO.
        /// </summary>
        internal static string TMO {
            get {
                return ResourceManager.GetString("TMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMO File(*.tmo)|*.tmo.
        /// </summary>
        internal static string TMOFileDescription {
            get {
                return ResourceManager.GetString("TMOFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long filename.
        /// </summary>
        internal static string TooLongFilename {
            get {
                return ResourceManager.GetString("TooLongFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file date time.
        /// </summary>
        internal static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all file date time.
        /// </summary>
        internal static string TouchAll {
            get {
                return ResourceManager.GetString("TouchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file date time.
        /// </summary>
        internal static string TouchDialogText {
            get {
                return ResourceManager.GetString("TouchDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSO.
        /// </summary>
        internal static string TSO {
            get {
                return ResourceManager.GetString("TSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera reset with new tso loaded.
        /// </summary>
        internal static string TSOLoadBehavior {
            get {
                return ResourceManager.GetString("TSOLoadBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pose animation is set with two or more displays and tmo in single purpose display and ctrl key + tso click in the tso click..
        /// </summary>
        internal static string TSOMessage {
            get {
                return ResourceManager.GetString("TSOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSO viewer.
        /// </summary>
        internal static string TSOViewerMenu {
            get {
                return ResourceManager.GetString("TSOViewerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacume arcs.db.
        /// </summary>
        internal static string VacumeArcsDB {
            get {
                return ResourceManager.GetString("VacumeArcsDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string WindowMenu {
            get {
                return ResourceManager.GetString("WindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP directory.
        /// </summary>
        internal static string ZipDirectory {
            get {
                return ResourceManager.GetString("ZipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP extract place.
        /// </summary>
        internal static string ZipExtractLocation {
            get {
                return ResourceManager.GetString("ZipExtractLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file behavior.
        /// </summary>
        internal static string ZipFileBehavior {
            get {
                return ResourceManager.GetString("ZipFileBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file extract behavior.
        /// </summary>
        internal static string ZipFileExtractBehavior {
            get {
                return ResourceManager.GetString("ZipFileExtractBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be Archive only.
        /// </summary>
        internal static string ZipFileOnly {
            get {
                return ResourceManager.GetString("ZipFileOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP RegExp..
        /// </summary>
        internal static string ZIPRegExp {
            get {
                return ResourceManager.GetString("ZIPRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string ZipsTabName {
            get {
                return ResourceManager.GetString("ZipsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:Mouse click.
        /// </summary>
        internal static string ZoomByClick {
            get {
                return ResourceManager.GetString("ZoomByClick", resourceCulture);
            }
        }
    }
}
