//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDCGExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDCGExplorer.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DCG Mods Reference Serverにアクセスする.
        /// </summary>
        internal static string AccessModsRefServer {
            get {
                return ResourceManager.GetString("AccessModsRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規タブで表示する.
        /// </summary>
        internal static string AlwaysNewTab {
            get {
                return ResourceManager.GetString("AlwaysNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP展開時にフォルダを表示する.
        /// </summary>
        internal static string AlwaysOpenFolderByExtract {
            get {
                return ResourceManager.GetString("AlwaysOpenFolderByExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書庫.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archiveがnullになりました.
        /// </summary>
        internal static string ArchiveIsNull {
            get {
                return ResourceManager.GetString("ArchiveIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーカイブが見つかりません.
        /// </summary>
        internal static string ArchiveNotFound {
            get {
                return ResourceManager.GetString("ArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCSディレクトリ.
        /// </summary>
        internal static string ArcsDirectory {
            get {
                return ResourceManager.GetString("ArcsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arcnames server.
        /// </summary>
        internal static string ArcsNameServer {
            get {
                return ResourceManager.GetString("ArcsNameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcs.
        /// </summary>
        internal static string ArcsTabName {
            get {
                return ResourceManager.GetString("ArcsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base.tahの読み込みでエラーが発生しました。.
        /// </summary>
        internal static string BaseTahReadError {
            get {
                return ResourceManager.GetString("BaseTahReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カメラ.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カメラ設定.
        /// </summary>
        internal static string CameraAutoCenter {
            get {
                return ResourceManager.GetString("CameraAutoCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回転中心.
        /// </summary>
        internal static string CameraCenter {
            get {
                return ResourceManager.GetString("CameraCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期視点.
        /// </summary>
        internal static string CameraTransition {
            get {
                return ResourceManager.GetString("CameraTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 種類.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タブを閉じる.
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コード.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突検出.
        /// </summary>
        internal static string CollisionDetection {
            get {
                return ResourceManager.GetString("CollisionDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突先TAH.
        /// </summary>
        internal static string CollisionedTAH {
            get {
                return ResourceManager.GetString("CollisionedTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突元.
        /// </summary>
        internal static string CollisionFrom {
            get {
                return ResourceManager.GetString("CollisionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突したtah.
        /// </summary>
        internal static string CollisionHTML_CollisionFrom {
            get {
                return ResourceManager.GetString("CollisionHTML_CollisionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突先.
        /// </summary>
        internal static string CollisionHTML_CollisionTo {
            get {
                return ResourceManager.GetString("CollisionHTML_CollisionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突.
        /// </summary>
        internal static string CollisionsTabName {
            get {
                return ResourceManager.GetString("CollisionsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 衝突先.
        /// </summary>
        internal static string CollisionTo {
            get {
                return ResourceManager.GetString("CollisionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梱包完了.
        /// </summary>
        internal static string CompressComplete {
            get {
                return ResourceManager.GetString("CompressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梱包中.
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース.
        /// </summary>
        internal static string DataBaseMenu {
            get {
                return ResourceManager.GetString("DataBaseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース設定.
        /// </summary>
        internal static string DatabaseSetting {
            get {
                return ResourceManager.GetString("DatabaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベースの構築・更新.
        /// </summary>
        internal static string DataBaseUpdate {
            get {
                return ResourceManager.GetString("DataBaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日時.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbファイルの削除ができませんでした。手動で削除して下さい。.
        /// </summary>
        internal static string DBFileDeleteError {
            get {
                return ResourceManager.GetString("DBFileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tahバージョン違いは衝突とみなさない.
        /// </summary>
        internal static string DifferVersionTah {
            get {
                return ResourceManager.GetString("DifferVersionTah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディレクトリ.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSOビューワにポーズを表示する.
        /// </summary>
        internal static string DisplayPoseTSOView {
            get {
                return ResourceManager.GetString("DisplayPoseTSOView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSOビューに表示する.
        /// </summary>
        internal static string DisplayTSOView {
            get {
                return ResourceManager.GetString("DisplayTSOView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新の情報を表示.
        /// </summary>
        internal static string DisplayUpdate {
            get {
                return ResourceManager.GetString("DisplayUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベースからのダウンロード.
        /// </summary>
        internal static string DownloadCaption {
            get {
                return ResourceManager.GetString("DownloadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新のデータベース情報を取得.
        /// </summary>
        internal static string DownloadLatestArcsnameszip {
            get {
                return ResourceManager.GetString("DownloadLatestArcsnameszip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注訳を入力....
        /// </summary>
        internal static string EditAnnotation {
            get {
                return ResourceManager.GetString("EditAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注訳の入力.
        /// </summary>
        internal static string EditAnnotationText {
            get {
                return ResourceManager.GetString("EditAnnotationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期設定.
        /// </summary>
        internal static string EditConfiguration {
            get {
                return ResourceManager.GetString("EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集中.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期設定.
        /// </summary>
        internal static string EditSystemDatabase {
            get {
                return ResourceManager.GetString("EditSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイルを編集する.
        /// </summary>
        internal static string EditTahFile {
            get {
                return ResourceManager.GetString("EditTahFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツリーを展開.
        /// </summary>
        internal static string ExpandTree {
            get {
                return ResourceManager.GetString("ExpandTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの展開に失敗しました.
        /// </summary>
        internal static string ExtractFailure {
            get {
                return ResourceManager.GetString("ExtractFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開失敗.
        /// </summary>
        internal static string ExtractFailureCaption {
            get {
                return ResourceManager.GetString("ExtractFailureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開中.
        /// </summary>
        internal static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを展開しました.
        /// </summary>
        internal static string ExtractSuccess {
            get {
                return ResourceManager.GetString("ExtractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展開成功.
        /// </summary>
        internal static string ExtractSuccessCaption {
            get {
                return ResourceManager.GetString("ExtractSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイルを展開する.
        /// </summary>
        internal static string ExtractTahFile {
            get {
                return ResourceManager.GetString("ExtractTahFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーカイブファイルの展開.
        /// </summary>
        internal static string ExtractZipFile {
            get {
                return ResourceManager.GetString("ExtractZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィギュア.
        /// </summary>
        internal static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの読み取りでエラーが発生しました。.
        /// </summary>
        internal static string FileReadError {
            get {
                return ResourceManager.GetString("FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル読み取り中.
        /// </summary>
        internal static string FileReading {
            get {
                return ResourceManager.GetString("FileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズ.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルタイプ.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが使用中です。.
        /// </summary>
        internal static string FileUsed {
            get {
                return ResourceManager.GetString("FileUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前提TAHを検索する.
        /// </summary>
        internal static string FindNoBaseMod {
            get {
                return ResourceManager.GetString("FindNoBaseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索された前提アーカイブファイル.
        /// </summary>
        internal static string FoundStrayArchive {
            get {
                return ResourceManager.GetString("FoundStrayArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前提TAH検索.
        /// </summary>
        internal static string FoundStrayTAH {
            get {
                return ResourceManager.GetString("FoundStrayTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハッシュコード.
        /// </summary>
        internal static string HashCode {
            get {
                return ResourceManager.GetString("HashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インターネットへのアクセスに失敗しました.
        /// </summary>
        internal static string HttpError {
            get {
                return ResourceManager.GetString("HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インストール済み.
        /// </summary>
        internal static string InstalledModsTabName {
            get {
                return ResourceManager.GetString("InstalledModsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前提アーカイブファイルを展開.
        /// </summary>
        internal static string InstallPreferredMods {
            get {
                return ResourceManager.GetString("InstallPreferredMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ライト.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常に3DCG Mods Reference Serverから最新情報を取得する.
        /// </summary>
        internal static string LookupModRefServer {
            get {
                return ResourceManager.GetString("LookupModRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダミーTAHファイルの作成.
        /// </summary>
        internal static string MakeDummyTAH {
            get {
                return ResourceManager.GetString("MakeDummyTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘビーセーブ形式で保存する.
        /// </summary>
        internal static string MakeHeavySaveFile {
            get {
                return ResourceManager.GetString("MakeHeavySaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイルを作成する.
        /// </summary>
        internal static string MakeTAHFile {
            get {
                return ResourceManager.GetString("MakeTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbnファイルの生成.
        /// </summary>
        internal static string MakeTbnDialogText {
            get {
                return ResourceManager.GetString("MakeTbnDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サムネイルを作成する.
        /// </summary>
        internal static string MakeThumbnail {
            get {
                return ResourceManager.GetString("MakeThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://3dcustom.ath.cx/TDCGExplorer/manual.html.
        /// </summary>
        internal static string MODRefServerUrl {
            get {
                return ResourceManager.GetString("MODRefServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD正規表現.
        /// </summary>
        internal static string MODRegExp {
            get {
                return ResourceManager.GetString("MODRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod ref. server.
        /// </summary>
        internal static string ModsRefServer {
            get {
                return ResourceManager.GetString("ModsRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいタブを開く.
        /// </summary>
        internal static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいTab.
        /// </summary>
        internal static string NewTabCaption {
            get {
                return ResourceManager.GetString("NewTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 何もしない.
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作はTAHディレクトリのみ実行できます.
        /// </summary>
        internal static string OnlyTAHDirectory {
            get {
                return ResourceManager.GetString("OnlyTAHDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作はTAHファイルのみ実行できます.
        /// </summary>
        internal static string OnlyTAHFile {
            get {
                return ResourceManager.GetString("OnlyTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作はTMOにのみ実行できます.
        /// </summary>
        internal static string OnlyTMOFile {
            get {
                return ResourceManager.GetString("OnlyTMOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作はTSOにのみ実行できます.
        /// </summary>
        internal static string OnlyTSOFile {
            get {
                return ResourceManager.GetString("OnlyTSOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されている階層以下のTAHをエディタで開く.
        /// </summary>
        internal static string OpenAllTAH {
            get {
                return ResourceManager.GetString("OpenAllTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーカイブ展開フォルダを開く.
        /// </summary>
        internal static string OpenArchive {
            get {
                return ResourceManager.GetString("OpenArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダを開く.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初に見つけた画像もしくはテキストを表示する.
        /// </summary>
        internal static string OpenGraphicsOrText {
            get {
                return ResourceManager.GetString("OpenGraphicsOrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初に見つけたテキストもしくは画像を表示する.
        /// </summary>
        internal static string OpenTextOrGraphics {
            get {
                return ResourceManager.GetString("OpenTextOrGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パーツ.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNGファイル(*.tdcgpose.png)|*.tdcgpose.png.
        /// </summary>
        internal static string PNGPoseFileDescription {
            get {
                return ResourceManager.GetString("PNGPoseFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNGファイル(*.tdcgsav.png)|*.tdcgsav.png.
        /// </summary>
        internal static string PNGSaveFileDescription {
            get {
                return ResourceManager.GetString("PNGSaveFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poseディレクトリ.
        /// </summary>
        internal static string PoseDirectory {
            get {
                return ResourceManager.GetString("PoseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーズファイル表示.
        /// </summary>
        internal static string PoseFileSetting {
            get {
                return ResourceManager.GetString("PoseFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIPを優先的に調べる.
        /// </summary>
        internal static string PreferredZipFile {
            get {
                return ResourceManager.GetString("PreferredZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個のzipを展開しました。.
        /// </summary>
        internal static string PrefZip1 {
            get {
                return ResourceManager.GetString("PrefZip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個のzipが見つかりませんでした。.
        /// </summary>
        internal static string PrefZip2 {
            get {
                return ResourceManager.GetString("PrefZip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前提zipは全てインストール済みです.
        /// </summary>
        internal static string PrefZip3 {
            get {
                return ResourceManager.GetString("PrefZip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string prefZip4 {
            get {
                return ResourceManager.GetString("prefZip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSDの読み込みでエラーが発生しました。.
        /// </summary>
        internal static string PSDFileReadError {
            get {
                return ResourceManager.GetString("PSDFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘビーセーブファイルを読み直す.
        /// </summary>
        internal static string ReloadHeavySaveFile {
            get {
                return ResourceManager.GetString("ReloadHeavySaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名を変更する.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描画完了....
        /// </summary>
        internal static string RenderingComplete {
            get {
                return ResourceManager.GetString("RenderingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描画中....
        /// </summary>
        internal static string RenderingNow {
            get {
                return ResourceManager.GetString("RenderingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 関連アーカイブを調べる.
        /// </summary>
        internal static string ResearchAssumptionArchive {
            get {
                return ResourceManager.GetString("ResearchAssumptionArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビューワをリセット.
        /// </summary>
        internal static string ResetTsoViwer {
            get {
                return ResourceManager.GetString("ResetTsoViwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名が一致する物も衝突とみなす.
        /// </summary>
        internal static string SameFileIsCollisioned {
            get {
                return ResourceManager.GetString("SameFileIsCollisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル保存中.
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乳.
        /// </summary>
        internal static string SaveFileParam0 {
            get {
                return ResourceManager.GetString("SaveFileParam0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姉＆妹.
        /// </summary>
        internal static string SaveFileParam1 {
            get {
                return ResourceManager.GetString("SaveFileParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二の腕.
        /// </summary>
        internal static string SaveFileParam2 {
            get {
                return ResourceManager.GetString("SaveFileParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 太もも.
        /// </summary>
        internal static string SaveFileParam3 {
            get {
                return ResourceManager.GetString("SaveFileParam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウエスト.
        /// </summary>
        internal static string SaveFileParam4 {
            get {
                return ResourceManager.GetString("SaveFileParam4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツリ眼たれ眼.
        /// </summary>
        internal static string SaveFileParam5 {
            get {
                return ResourceManager.GetString("SaveFileParam5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やわらか.
        /// </summary>
        internal static string SaveFileParam6 {
            get {
                return ResourceManager.GetString("SaveFileParam6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブファイル.
        /// </summary>
        internal static string SaveFilesTabName {
            get {
                return ResourceManager.GetString("SaveFilesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブファイルビューア.
        /// </summary>
        internal static string SaveFileViewer {
            get {
                return ResourceManager.GetString("SaveFileViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH形式の保存.
        /// </summary>
        internal static string SaveTAHFile {
            get {
                return ResourceManager.GetString("SaveTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたtmoファイルを保存する.
        /// </summary>
        internal static string SaveTMOFile {
            get {
                return ResourceManager.GetString("SaveTMOFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索完了。行をダブルクリックすると、そのファイルにジャンプします。.
        /// </summary>
        internal static string SearchComplete {
            get {
                return ResourceManager.GetString("SearchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索文字列.
        /// </summary>
        internal static string SearchDialogLabel {
            get {
                return ResourceManager.GetString("SearchDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        internal static string SearchDialogText {
            get {
                return ResourceManager.GetString("SearchDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索中.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーカイブも検索する.
        /// </summary>
        internal static string SearchWithZipFile {
            get {
                return ResourceManager.GetString("SearchWithZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て選択.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先のファイルを選択してください.
        /// </summary>
        internal static string SelectSaveFileName {
            get {
                return ResourceManager.GetString("SelectSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マニュアルの表示.
        /// </summary>
        internal static string ShowManual {
            get {
                return ResourceManager.GetString("ShowManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSOプレビューを表示する.
        /// </summary>
        internal static string ShowTSOPreview {
            get {
                return ResourceManager.GetString("ShowTSOPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン....
        /// </summary>
        internal static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動時の設定.
        /// </summary>
        internal static string StartupSetting {
            get {
                return ResourceManager.GetString("StartupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前提TAHが無いTAH名.
        /// </summary>
        internal static string StrayTAH {
            get {
                return ResourceManager.GetString("StrayTAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なベースTBN名.
        /// </summary>
        internal static string StrayTBN {
            get {
                return ResourceManager.GetString("StrayTBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DCG MODS Referenceサーバから最新情報を取得しました.
        /// </summary>
        internal static string SuccessModRefServer {
            get {
                return ResourceManager.GetString("SuccessModRefServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アニメーション開始.
        /// </summary>
        internal static string SwitchToMortionEnabled {
            get {
                return ResourceManager.GetString("SwitchToMortionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タブブラウザ.
        /// </summary>
        internal static string TabBrowser {
            get {
                return ResourceManager.GetString("TabBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タグ.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagnames server.
        /// </summary>
        internal static string TagNameServer {
            get {
                return ResourceManager.GetString("TagNameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タグ.
        /// </summary>
        internal static string TagsTabName {
            get {
                return ResourceManager.GetString("TagsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル展開完了.
        /// </summary>
        internal static string TAHDecryptComplete {
            get {
                return ResourceManager.GetString("TAHDecryptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHエディタ.
        /// </summary>
        internal static string TAHEditor {
            get {
                return ResourceManager.GetString("TAHEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルのカテゴリを変更する.
        /// </summary>
        internal static string TAHEditorChangeCategory {
            get {
                return ResourceManager.GetString("TAHEditorChangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルの色番号を変更する.
        /// </summary>
        internal static string TAHEditorChangeColorCode {
            get {
                return ResourceManager.GetString("TAHEditorChangeColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH情報を変更する.
        /// </summary>
        internal static string TAHEditorChangeTAHInformation {
            get {
                return ResourceManager.GetString("TAHEditorChangeTAHInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルをTAHに梱包する.
        /// </summary>
        internal static string TAHEditorComposeTAHFile {
            get {
                return ResourceManager.GetString("TAHEditorComposeTAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルの削除.
        /// </summary>
        internal static string TAHEditorFileDelete {
            get {
                return ResourceManager.GetString("TAHEditorFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したtsoファイルのtbnを生成する.
        /// </summary>
        internal static string TAHEditorMakeTBN {
            get {
                return ResourceManager.GetString("TAHEditorMakeTBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色番号は二文字で指定して下さい.
        /// </summary>
        internal static string TAHEditorNewColorNoError {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい色番号.
        /// </summary>
        internal static string TAHEditorNewColorNoLabel {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色番号の変更.
        /// </summary>
        internal static string TAHEditorNewColorNoText {
            get {
                return ResourceManager.GetString("TAHEditorNewColorNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH編集先.
        /// </summary>
        internal static string TAHEditorPlace {
            get {
                return ResourceManager.GetString("TAHEditorPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルの名前を変更する.
        /// </summary>
        internal static string TAHEditorRename {
            get {
                return ResourceManager.GetString("TAHEditorRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名の変更.
        /// </summary>
        internal static string TAHEditorRenameLabel {
            get {
                return ResourceManager.GetString("TAHEditorRenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい名前.
        /// </summary>
        internal static string TAHEditorRenameText {
            get {
                return ResourceManager.GetString("TAHEditorRenameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルを保存する.
        /// </summary>
        internal static string TAHEditorSaveSelectedFile {
            get {
                return ResourceManager.GetString("TAHEditorSaveSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBNの属性.
        /// </summary>
        internal static string TAHEditorTbnCatChangeLabel {
            get {
                return ResourceManager.GetString("TAHEditorTbnCatChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBNの属性変更.
        /// </summary>
        internal static string TAHEditorTbnCatChangeText {
            get {
                return ResourceManager.GetString("TAHEditorTbnCatChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル読み取り完了.
        /// </summary>
        internal static string TAHEncryptComplete {
            get {
                return ResourceManager.GetString("TAHEncryptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル.
        /// </summary>
        internal static string TAHFile {
            get {
                return ResourceManager.GetString("TAHFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル(*.tah)|*.tah.
        /// </summary>
        internal static string TAHFileDescription {
            get {
                return ResourceManager.GetString("TAHFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tahファイルが4GBを超えます。集約するtahファイルは4GB以下にしてください。.
        /// </summary>
        internal static string TAHFileLimitError {
            get {
                return ResourceManager.GetString("TAHFileLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル名.
        /// </summary>
        internal static string TAHFilename {
            get {
                return ResourceManager.GetString("TAHFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHの読み取りでエラーが発生しました。.
        /// </summary>
        internal static string TAHFileReadError {
            get {
                return ResourceManager.GetString("TAHFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHファイル読み取り中....
        /// </summary>
        internal static string TAHFileReading {
            get {
                return ResourceManager.GetString("TAHFileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAH内部ファイル検索....
        /// </summary>
        internal static string tahfilesearch {
            get {
                return ResourceManager.GetString("tahfilesearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHヘッダー情報.
        /// </summary>
        internal static string TAHInformation {
            get {
                return ResourceManager.GetString("TAHInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAHバージョン.
        /// </summary>
        internal static string TAHVersion {
            get {
                return ResourceManager.GetString("TAHVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbnファイル解析中.
        /// </summary>
        internal static string TBNAnalyze {
            get {
                return ResourceManager.GetString("TBNAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:眉.
        /// </summary>
        internal static string TbnCat0 {
            get {
                return ResourceManager.GetString("TbnCat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:八重歯.
        /// </summary>
        internal static string TbnCat1 {
            get {
                return ResourceManager.GetString("TbnCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:ほくろ.
        /// </summary>
        internal static string TbnCat2 {
            get {
                return ResourceManager.GetString("TbnCat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:イヤリング.
        /// </summary>
        internal static string TbnCat3 {
            get {
                return ResourceManager.GetString("TbnCat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:身体.
        /// </summary>
        internal static string TbnCatA {
            get {
                return ResourceManager.GetString("TbnCatA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B:頭髪前.
        /// </summary>
        internal static string TbnCatB {
            get {
                return ResourceManager.GetString("TbnCatB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:頭髪後.
        /// </summary>
        internal static string TbnCatC {
            get {
                return ResourceManager.GetString("TbnCatC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:頭髪生え際.
        /// </summary>
        internal static string TbnCatD {
            get {
                return ResourceManager.GetString("TbnCatD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:瞳.
        /// </summary>
        internal static string TbnCatE {
            get {
                return ResourceManager.GetString("TbnCatE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景.
        /// </summary>
        internal static string TbnCatEx0 {
            get {
                return ResourceManager.GetString("TbnCatEx0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ｈシーン.
        /// </summary>
        internal static string TbnCatEx1 {
            get {
                return ResourceManager.GetString("TbnCatEx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:ブラ.
        /// </summary>
        internal static string TbnCatF {
            get {
                return ResourceManager.GetString("TbnCatF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G:全身下着.
        /// </summary>
        internal static string TbnCatG {
            get {
                return ResourceManager.GetString("TbnCatG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H:パンツ.
        /// </summary>
        internal static string TbnCatH {
            get {
                return ResourceManager.GetString("TbnCatH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I:靴下.
        /// </summary>
        internal static string TbnCatI {
            get {
                return ResourceManager.GetString("TbnCatI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J:上着.
        /// </summary>
        internal static string TbnCatJ {
            get {
                return ResourceManager.GetString("TbnCatJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K:全身上着.
        /// </summary>
        internal static string TbnCatK {
            get {
                return ResourceManager.GetString("TbnCatK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:上着オプション.
        /// </summary>
        internal static string TbnCatL {
            get {
                return ResourceManager.GetString("TbnCatL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M:スカート.
        /// </summary>
        internal static string TbnCatM {
            get {
                return ResourceManager.GetString("TbnCatM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:尻尾.
        /// </summary>
        internal static string TbnCatN {
            get {
                return ResourceManager.GetString("TbnCatN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:靴.
        /// </summary>
        internal static string TbnCatO {
            get {
                return ResourceManager.GetString("TbnCatO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P:頭部装備.
        /// </summary>
        internal static string TbnCatP {
            get {
                return ResourceManager.GetString("TbnCatP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q:眼鏡.
        /// </summary>
        internal static string TbnCatQ {
            get {
                return ResourceManager.GetString("TbnCatQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R:首輪.
        /// </summary>
        internal static string TbnCatR {
            get {
                return ResourceManager.GetString("TbnCatR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:腕装備.
        /// </summary>
        internal static string TbnCatS {
            get {
                return ResourceManager.GetString("TbnCatS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:背中.
        /// </summary>
        internal static string TbnCatT {
            get {
                return ResourceManager.GetString("TbnCatT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U:頭髪オプション.
        /// </summary>
        internal static string TbnCatU {
            get {
                return ResourceManager.GetString("TbnCatU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V:眼帯.
        /// </summary>
        internal static string TbnCatV {
            get {
                return ResourceManager.GetString("TbnCatV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W:タイツ・ガーター.
        /// </summary>
        internal static string TbnCatW {
            get {
                return ResourceManager.GetString("TbnCatW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:手首.
        /// </summary>
        internal static string TbnCatX {
            get {
                return ResourceManager.GetString("TbnCatX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:リボン.
        /// </summary>
        internal static string TbnCatY {
            get {
                return ResourceManager.GetString("TbnCatY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:手持ち.
        /// </summary>
        internal static string TbnCatZ {
            get {
                return ResourceManager.GetString("TbnCatZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbnの読み込みでエラーが発生しました。.
        /// </summary>
        internal static string TBNReadError {
            get {
                return ResourceManager.GetString("TBNReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDCGディレクトリ.
        /// </summary>
        internal static string TDCGDirectory {
            get {
                return ResourceManager.GetString("TDCGDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMO.
        /// </summary>
        internal static string TMO {
            get {
                return ResourceManager.GetString("TMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMOファイル(*.tmo)|*.tmo.
        /// </summary>
        internal static string TMOFileDescription {
            get {
                return ResourceManager.GetString("TMOFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字数が長すぎます.
        /// </summary>
        internal static string TooLongFilename {
            get {
                return ResourceManager.GetString("TooLongFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルのタイムスタンプを変更する.
        /// </summary>
        internal static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てのファイルの日時を変更する.
        /// </summary>
        internal static string TouchAll {
            get {
                return ResourceManager.GetString("TouchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイムスタンプの変更.
        /// </summary>
        internal static string TouchDialogText {
            get {
                return ResourceManager.GetString("TouchDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSO.
        /// </summary>
        internal static string TSO {
            get {
                return ResourceManager.GetString("TSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規TSOロード時、カメラ設定をリセットする.
        /// </summary>
        internal static string TSOLoadBehavior {
            get {
                return ResourceManager.GetString("TSOLoadBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tsoクリックで単体表示,ctrlキー+tsoクリックで複数表示,tmoでポーズ・アニメーションを設定.
        /// </summary>
        internal static string TSOMessage {
            get {
                return ResourceManager.GetString("TSOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSOビューワ.
        /// </summary>
        internal static string TSOViewerMenu {
            get {
                return ResourceManager.GetString("TSOViewerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arcs.dbを再圧縮する.
        /// </summary>
        internal static string VacumeArcsDB {
            get {
                return ResourceManager.GetString("VacumeArcsDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウインドウ.
        /// </summary>
        internal static string WindowMenu {
            get {
                return ResourceManager.GetString("WindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIPディレクトリ.
        /// </summary>
        internal static string ZipDirectory {
            get {
                return ResourceManager.GetString("ZipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP展開先.
        /// </summary>
        internal static string ZipExtractLocation {
            get {
                return ResourceManager.GetString("ZipExtractLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP選択時の動作.
        /// </summary>
        internal static string ZipFileBehavior {
            get {
                return ResourceManager.GetString("ZipFileBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP展開時の処理.
        /// </summary>
        internal static string ZipFileExtractBehavior {
            get {
                return ResourceManager.GetString("ZipFileExtractBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作は圧縮ファイルにのみ実行できます.
        /// </summary>
        internal static string ZipFileOnly {
            get {
                return ResourceManager.GetString("ZipFileOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP正規表現.
        /// </summary>
        internal static string ZIPRegExp {
            get {
                return ResourceManager.GetString("ZIPRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーカイブ.
        /// </summary>
        internal static string ZipsTabName {
            get {
                return ResourceManager.GetString("ZipsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリックで拡大縮小.
        /// </summary>
        internal static string ZoomByClick {
            get {
                return ResourceManager.GetString("ZoomByClick", resourceCulture);
            }
        }
    }
}
